<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Regression &amp; Interpretability Challenge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regression &amp; Interpretability Challenge</h1>
<p class="subtitle lead">Don’t Trust Linear Models – The Perils of Non-Linearity</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="regression-challenge---linear-model-interpretability" class="level1">
<h1>🗑️ Regression Challenge - Linear Model Interpretability</h1>
<section id="challenge-overview" class="level2">
<h2 class="anchored" data-anchor-id="challenge-overview">Challenge Overview</h2>
<p><strong>Your Mission:</strong> Create a comprehensive Quarto document that demonstrates the dangers of trusting linear models when relationships are non-linear, analyzes the interpretability issues that arise, and presents compelling visual evidence of why we need to be skeptical of regression results. Then render the document to HTML and deploy it via GitHub Pages using the starter repository workflow.</p>
</section>
<section id="problem-violating-the-assumption-of-linearity" class="level2">
<h2 class="anchored" data-anchor-id="problem-violating-the-assumption-of-linearity">Problem Violating the Assumption of Linearity🎯</h2>
<blockquote class="blockquote">
<p>“We need to stop believing much of the empirical work we’ve been doing.” - Christopher H. Achen</p>
</blockquote>
<p><strong>The Core Problem:</strong> When researchers need to ‘control for’ variables using linear regression, what happens when the relationships are non-linear?</p>
<p><strong>What does “control for” mean?</strong> Imagine you’re studying whether social media causes anxiety. You know that stress is a major cause of anxiety, and you also suspect that social media use might cause anxiety. So you need to “control for” stress to see if social media has an independent effect on anxiety. You want to ask: “If two people have the same stress level, does the one who uses more social media have higher anxiety?”</p>
<p>Your challenge is to explore the simple example below and show how this happens:</p>
<p><span class="math display">\[
\begin{aligned}
A &amp;\equiv \textrm{Anxiety Level measured by fMRI activity}\\
S &amp;\equiv \textrm{Stress Level measured by cortisol level in blood}\\
T &amp;\equiv \textrm{\# of minutes on social media in last 24 hours}
\end{aligned}
\]</span></p>
<p>Let’s assume we <strong>know</strong> the relationship among these variables is as follows:</p>
<p><span class="math display">\[
Anxiety = Stress + 0.1 \times Time
\]</span></p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>🔍 Understanding the True Relationship: Implied Coefficients
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Critical Point:</strong> Students often miss that this specific equation implies specific coefficient values in the generic multiple regression framework.</p>
<p><strong>The Generic Multiple Regression Equation:</strong> <span class="math display">\[
Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \epsilon
\]</span></p>
<p><strong>In Our Case:</strong> <span class="math display">\[
Anxiety = \beta_0 + \beta_1 \times Stress + \beta_2 \times Time + \epsilon
\]</span></p>
<p><strong>The True Coefficients (what we “know”):</strong></p>
<ul>
<li><span class="math inline">\(\beta_0 = 0\)</span> (intercept is zero)</li>
<li><span class="math inline">\(\beta_1 = 1\)</span> (coefficient on Stress is 1)<br>
</li>
<li><span class="math inline">\(\beta_2 = 0.1\)</span> (coefficient on Time is 0.1)</li>
</ul>
<p><strong>Why This Matters:</strong> When we run regression analysis, we’re trying to estimate these <span class="math inline">\(\beta\)</span> coefficients. If our regression gives us coefficients that are very different from these true values, we know our model is wrong—even if it has good statistical fit!</p>
</div>
</div>
<section id="the-data-generation-process" class="level3">
<h3 class="anchored" data-anchor-id="the-data-generation-process">The Data Generation Process</h3>
<div class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>observDF</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="tbl-observations" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-observations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Observed data with known true relationships
</figcaption>
<div aria-describedby="tbl-observations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Stress</th>
<th data-quarto-table-cell-role="th">StressSurvey</th>
<th data-quarto-table-cell-role="th">Time</th>
<th data-quarto-table-cell-role="th">Anxiety</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>0</td>
<td>0</td>
<td>0.0</td>
<td>0.00</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>0</td>
<td>0</td>
<td>1.0</td>
<td>0.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>0</td>
<td>0</td>
<td>1.0</td>
<td>0.10</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>8</td>
<td>9</td>
<td>2.0</td>
<td>8.20</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>8</td>
<td>9</td>
<td>2.0</td>
<td>8.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>8</td>
<td>9</td>
<td>2.1</td>
<td>8.21</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="questions-to-answer-for-75-grade-on-challenge" class="level3">
<h3 class="anchored">Questions to Answer for 75% Grade on Challenge</h3>
<ol type="1">
<li><strong>Bivariate Regression Analysis with StressSurvey:</strong> Run a bivariate regression of Anxiety on StressSurvey. What are the estimated coefficients? How do they compare to the true relationship?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>📈 Bivariate Regression Analysis with StressSurvey
</div>
</div>
<div class="callout-body-container callout-body">
<p>We performed a bivariate linear regression of <strong>Anxiety</strong> on <strong>StressSurvey</strong> using the provided dataset.</p>
<div id="bivariate-model-execution" class="cell" data-execution_count="3">
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.901
Model:                            OLS   Adj. R-squared:                  0.893
Method:                 Least Squares   F-statistic:                     118.4
Date:                Mon, 10 Nov 2025   Prob (F-statistic):           6.68e-08
Time:                        09:54:51   Log-Likelihood:                -27.079
No. Observations:                  15   AIC:                             58.16
Df Residuals:                      13   BIC:                             59.57
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const           -1.5240      0.707     -2.156      0.050      -3.051       0.003
StressSurvey     1.0470      0.096     10.883      0.000       0.839       1.255
==============================================================================
Omnibus:                        2.125   Durbin-Watson:                   0.545
Prob(Omnibus):                  0.346   Jarque-Bera (JB):                1.642
Skew:                          -0.701   Prob(JB):                        0.440
Kurtosis:                       2.186   Cond. No.                         12.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
Intercept: -1.5240
Slope: 1.0470
R-squared: 0.9011</code></pre>
</div>
</div>
<section id="estimated-model" class="level3">
<h3 class="anchored" data-anchor-id="estimated-model">🔢 Estimated Model</h3>
<p>The fitted regression equation is:</p>
<p><span class="math display">\[
\text{Anxiety} = -1.5240 + 1.0470 \cdot \text{StressSurvey}
\]</span></p>
<ul>
<li><strong>Intercept</strong>: -1.5240<br>
</li>
<li><strong>Slope</strong>: 1.0470<br>
</li>
<li><strong>R²</strong>: High, indicating strong linear association</li>
</ul>
</section>
<section id="comparison-to-true-relationship" class="level3">
<h3 class="anchored" data-anchor-id="comparison-to-true-relationship">🧠 Comparison to True Relationship</h3>
<p>The true generative model is assumed to be:</p>
<p><span class="math display">\[
\text{Anxiety} = \text{Stress} + 0.1 \cdot \text{Time}
\]</span></p>
<ul>
<li><strong>StressSurvey</strong> is not part of the true model; it’s a proxy for Stress.</li>
<li>The estimated slope (1.0470) captures correlation but not causation.</li>
<li>The intercept deviates significantly due to omitted variable bias (Time not included).</li>
<li>The model fit is statistically strong but <strong>misspecified</strong> relative to the true structure.</li>
</ul>
</section>
<section id="insight" class="level3">
<h3 class="anchored" data-anchor-id="insight">✅ Insight</h3>
<p>While the regression on StressSurvey yields a strong fit, it does not reflect the true underlying relationship. Including both <strong>Stress</strong> and <strong>Time</strong> as predictors would yield a more accurate and interpretable model.</p>
</section>
</div>
</div>
<ol start="2" type="1">
<li><strong>Visualization of Bivariate Relationship:</strong> Create a scatter plot with the regression line showing the relationship between StressSurvey and Anxiety. Comment on the fit and any potential issues.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>📊 Visualization Summary: StressSurvey vs Anxiety
</div>
</div>
<div class="callout-body-container callout-body">
<p>The scatter plot illustrates the relationship between <strong>StressSurvey</strong> and <strong>Anxiety</strong>, with observed data points overlaid by a fitted regression line. The line follows the upward trend in the data, suggesting a strong linear association. Clusters at StressSurvey levels 3, 6, 9, and 12 show consistent increases in Anxiety, reinforcing the model’s predictive alignment.</p>
<div id="plotting-regression-line--r2" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/plotting-regression-line--r2-output-1.png" id="plotting-regression-line--r2-1" width="662" height="449" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/plotting-regression-line--r2-output-2.png" id="plotting-regression-line--r2-2" width="670" height="449" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<section id="model-fit" class="level2">
<h2 class="anchored" data-anchor-id="model-fit">📈 Model Fit</h2>
<p>The bivariate regression yields the following equation:</p>
<p><span class="math display">\[
\text{Anxiety} = -1.5240 + 1.0470 \cdot \text{StressSurvey}
\]</span></p>
<ul>
<li><strong>R² ≈ 0.9011</strong>, indicating that StressSurvey explains nearly all the variation in Anxiety.</li>
<li>The regression line passes through the center of the data clusters, suggesting a statistically strong fit.</li>
</ul>
<hr>
</section>
<section id="potential-issues" class="level2">
<h2 class="anchored" data-anchor-id="potential-issues">⚠️ Potential Issues</h2>
<p>Despite the high R², the model is <strong>misspecified</strong> relative to the true generative process:</p>
<ul>
<li>The true relationship is: <span class="math display">\[
\text{Anxiety} = \text{Stress} + 0.1 \cdot \text{Time}
\]</span> StressSurvey is not a direct input to Anxiety—it likely acts as a proxy for Stress.</li>
<li><strong>Omitted Variable Bias</strong>: Time and Stress are excluded, which distorts the intercept and inflates the slope.</li>
<li><strong>Intercept Bias</strong>: The estimated intercept (-1.5240) deviates significantly from the true model’s implied intercept (~0.01).</li>
<li><strong>Collinearity Risk</strong>: If StressSurvey is derived from Stress, the model may capture correlation without reflecting causation.</li>
</ul>
</section>
</div>
</div>
<ol start="3" type="1">
<li><strong>Bivariate Regression Analysis with Time:</strong> Run a bivariate regression of Anxiety on Time. What are the estimated coefficients? How do they compare to the true relationship?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>📈 Bivariate Regression Analysis with Time
</div>
</div>
<div class="callout-body-container callout-body">
<p>We performed a bivariate linear regression of <strong>Anxiety</strong> on <strong>Time</strong> using the observed dataset.</p>
<section id="estimated-model-1" class="level3">
<h3 class="anchored" data-anchor-id="estimated-model-1">🔢 Estimated Model</h3>
<p>The fitted regression equation is:</p>
<p><span class="math display">\[
\text{Anxiety} = -3.6801 + 5.3406 \cdot \text{Time}
\]</span></p>
<ul>
<li><strong>Intercept</strong>: -3.6801<br>
</li>
<li><strong>Slope</strong>: 5.3406</li>
</ul>
<div id="91cb4189" class="cell" data-execution_count="5">
<div class="cell-output cell-output-stdout">
<pre><code>Estimated Intercept: -3.6801
Estimated Slope: 5.3406
R-squared: 0.5630</code></pre>
</div>
</div>
</section>
<section id="comparison-to-true-relationship-1" class="level3">
<h3 class="anchored" data-anchor-id="comparison-to-true-relationship-1">🧠 Comparison to True Relationship</h3>
<p>The true generative model is:</p>
<p><span class="math display">\[
\text{Anxiety} = \text{Stress} + 0.1 \cdot \text{Time}
\]</span></p>
<ul>
<li>The estimated model <strong>omits Stress</strong>, a key predictor.</li>
<li>As a result, the slope (5.3406) is <strong>inflated</strong>, absorbing the effect of both Stress and Time.</li>
<li>The intercept is <strong>biased downward</strong>, reflecting the missing Stress contribution at Time = 0.</li>
</ul>
</section>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">⚠️ Interpretation</h3>
<p>While the model shows a strong statistical fit, it is <strong>misspecified</strong>. Time alone cannot explain Anxiety accurately without accounting for Stress. This highlights the importance of including all relevant predictors when modeling real-world relationships.</p>
</section>
</div>
</div>
<ol start="4" type="1">
<li><strong>Visualization of Bivariate Relationship:</strong> Create a scatter plot with the regression line showing the relationship between Time and Anxiety. Comment on the fit and any potential issues.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Visualization of Bivariate Relationship b/w Time and Anxiety
</div>
</div>
<section id="bivariate-regression-anxiety-vs-time" class="level2 callout-body-container callout-body">
<h2 class="anchored" data-anchor-id="bivariate-regression-anxiety-vs-time">Bivariate Regression: Anxiety vs Time</h2>
<div id="e615e72c" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-7-output-1.png" width="662" height="449" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<section id="scatter-plot-insights" class="level3">
<h3 class="anchored" data-anchor-id="scatter-plot-insights">📉 Scatter Plot Insights</h3>
<ul>
<li>The scatter plot shows a <strong>clustered pattern</strong> at lower Time values (0–2), with Anxiety values ranging from 0 to 2.2.</li>
<li>However, <strong>three extreme outliers</strong> (Anxiety = 8.2 and 12.22 at Time ≈ 2.0–2.2) <strong>skew the regression line upward</strong>, inflating the slope and reducing model reliability.</li>
</ul>
</section>
<section id="potential-issues-1" class="level3">
<h3 class="anchored" data-anchor-id="potential-issues-1">⚠️ Potential Issues</h3>
<ul>
<li><strong>Outliers</strong>: The data points at Time ≈ 2.0–2.2 with Anxiety &gt; 8 are <strong>inconsistent with the true model</strong> (Anxiety = Stress + 0.1 × Time). These likely represent data entry errors or a different regime.</li>
<li><strong>Multicollinearity</strong>: Since Anxiety is known to depend on both Stress and Time, omitting Stress from the model introduces <strong>omitted variable bias</strong>.</li>
<li><strong>Non-linearity</strong>: The true relationship is additive with Stress, not purely linear in Time.</li>
</ul>
</section>
</section>
</div>
<ol start="5" type="1">
<li><strong>Multiple Regression Analysis:</strong> Run a multiple regression of Anxiety on both <strong>StressSurvey</strong> and Time. What are the estimated coefficients? How do they compare to the true relationship?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Multiple Regression Analysis
</div>
</div>
<div class="callout-body-container callout-body">
<section id="estimated-coefficients" class="level3">
<h3 class="anchored" data-anchor-id="estimated-coefficients">Estimated coefficients:</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Coefficient</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td style="text-align: right;">0.59</td>
</tr>
<tr class="even">
<td>StressSurvey</td>
<td style="text-align: right;">1.43</td>
</tr>
<tr class="odd">
<td>Time</td>
<td style="text-align: right;">-2.78</td>
</tr>
</tbody>
</table>
</section>
<section id="comparison-to-true-relationship-2" class="level3">
<h3 class="anchored" data-anchor-id="comparison-to-true-relationship-2">📐 Comparison to True Relationship</h3>
<p>Specified the true relationship is:</p>
<p><span class="math display">\[
  \text{Anxiety} = \text{Stress} + 0.1 \cdot \text{Time}
  \]</span></p>
<p><strong><em>This implies:</em></strong></p>
<ul>
<li>Stress has a 1.0 coefficient</li>
<li>Time has a +0.1 coefficient</li>
<li>No intercept</li>
</ul>
<p><strong><em>However, in our regression:</em></strong></p>
<ul>
<li>StressSurvey (a proxy for Stress) is overestimated at <strong>1.43</strong></li>
<li>Time is strongly underestimated and even negative, at <strong>–2.78</strong></li>
<li>A <strong>non-zero</strong> intercept appears, which isn’t part of the true relationship</li>
</ul>
</section>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>🎯 Remember the True Coefficients!
</div>
</div>
<div class="callout-body-container callout-body">
<p>When analyzing your multiple regression results, compare them to the <strong>true relationship</strong> we established:</p>
<p><strong>True Coefficients:</strong></p>
<ul>
<li>Intercept (<span class="math inline">\(\beta_0\)</span>) = 0</li>
<li>Stress coefficient (<span class="math inline">\(\beta_1\)</span>) = 1<br>
</li>
<li>Time coefficient (<span class="math inline">\(\beta_2\)</span>) = 0.1</li>
</ul>
<p><strong>Key Questions:</strong></p>
<ul>
<li>Are your estimated coefficients close to these true values?</li>
<li>If not, what does this tell you about the reliability of your regression model?</li>
<li>Even if your R-squared is high, are the coefficients telling the right story?</li>
</ul>
</div>
</div>
</section>
<section id="questions-to-answer-for-85-grade-on-challenge" class="level3">
<h3 class="anchored" data-anchor-id="questions-to-answer-for-85-grade-on-challenge">Questions to Answer for 85% Grade on Challenge</h3>
<ol start="6" type="1">
<li><strong>Multiple Regression Analysis:</strong> Run a multiple regression of Anxiety on both <strong>Stress</strong> and Time. What are the estimated coefficients? How do they compare to the true relationship?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Multiple regression of Anxiety on both <strong>Stress</strong> and <strong>Time</strong>
</div>
</div>
<div class="callout-body-container callout-body">
<section id="estimated-regression-coefficients" class="level3">
<h3 class="anchored" data-anchor-id="estimated-regression-coefficients">📊 Estimated Regression Coefficients</h3>
<ul>
<li>Intercept: –0.0003</li>
<li>Stress coefficient: 1.0000</li>
<li>Time coefficient: 0.1000</li>
</ul>
</section>
<section id="comparison-to-true-relationship-3" class="level3">
<h3 class="anchored" data-anchor-id="comparison-to-true-relationship-3">✅ Comparison to True Relationship</h3>
<p>True relationship:</p>
<p><span class="math display">\[
  \text{Anxiety} = \text{Stress} + 0.1 \cdot \text{Time}
  \]</span></p>
</section>
<section id="the-estimated-coefficients-match-this-exactly" class="level3">
<h3 class="anchored" data-anchor-id="the-estimated-coefficients-match-this-exactly">The estimated coefficients match this exactly:</h3>
<ul>
<li>Stress: 1.0000 (true: 1.0)</li>
<li>Time: 0.1000 (true: 0.1)</li>
<li>Intercept: ≈ 0 (negligible)</li>
</ul>
</section>
<section id="interpretation-1" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-1">🔍 Interpretation</h3>
<ul>
<li>The regression <strong>perfectly</strong> recovers the <strong>true</strong> relationship.</li>
<li>This confirms that the observed <strong>Anxiety</strong> values were generated using the formula provided, with <strong>no added noise</strong>.</li>
<li>The <strong>near-zero</strong> intercept suggests <strong>no</strong> systematic bias.</li>
</ul>
</section>
</div>
</div>
<ol start="7" type="1">
<li><strong>Model Comparison:</strong> Compare the R-squared values and coefficient interpretations between the two multiple regression models. Do both models show statistical significance in all of their coefficient estimates? What does this tell you about the real-world implications of multiple regression results?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Model Comparison
</div>
</div>
<div class="callout-body-container callout-body">
<section id="coefficient-comparison" class="level3">
<h3 class="anchored" data-anchor-id="coefficient-comparison">Coefficient Comparison</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;">Intercept</th>
<th style="text-align: right;">StressSurvey</th>
<th style="text-align: right;">Stress</th>
<th style="text-align: right;">Time</th>
<th style="text-align: right;">R2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>StressSurvey</td>
<td style="text-align: right;">0.59</td>
<td style="text-align: right;">1.43</td>
<td style="text-align: right;">NaN</td>
<td style="text-align: right;">-2.78</td>
<td style="text-align: right;">0.94</td>
</tr>
<tr class="even">
<td>Stress</td>
<td style="text-align: right;">~0</td>
<td style="text-align: right;">NaN</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">1.00</td>
</tr>
</tbody>
</table>
</section>
<section id="statistical-significance-of-coefficients" class="level3">
<h3 class="anchored" data-anchor-id="statistical-significance-of-coefficients">📊 Statistical Significance of Coefficients</h3>
<ol type="1">
<li>Model: Anxiety ~ StressSurvey + Time</li>
</ol>
<ul>
<li>StressSurvey: Statistically significant (p-value ≪ 0.05)</li>
<li>Time: Not significant (p-value ≫ 0.05)</li>
<li>Intercept: Significant</li>
</ul>
<ol start="2" type="1">
<li>Model: Anxiety ~ Stress + Time</li>
</ol>
<ul>
<li>Stress: Statistically significant (p-value ≪ 0.05)</li>
<li>Time: Statistically significant (p-value ≪ 0.05)</li>
<li>Intercept: Not significant (p-value ≈ 1.0)</li>
</ul>
</section>
<section id="real-world-implications" class="level3">
<h3 class="anchored" data-anchor-id="real-world-implications">🧠 Real-World Implications</h3>
<p><strong>✅ Significance ≠ Importance</strong></p>
<ul>
<li>In the StressSurvey model, Time appears insignificant, even though we know from the true relationship that Time contributes meaningfully (0.1·Time).</li>
<li>This shows that multicollinearity or poor proxy variables (like StressSurvey) can distort significance tests.</li>
</ul>
<p><strong>🔍 Model Specification Matters</strong></p>
<ul>
<li>The Stress model correctly identifies both predictors as significant, aligning with the true data-generating process.</li>
<li>This highlights the importance of using accurate, well-defined predictors. Poor proxies can lead to misleading inferences.</li>
</ul>
<p><strong>⚠️ Don’t Trust Significance Alone</strong></p>
<p><strong><em>Statistical significance is sensitive to:</em></strong></p>
<ul>
<li>Sample size</li>
<li>Noise</li>
<li>Collinearity</li>
<li>Model misspecification</li>
<li>A non-significant coefficient doesn’t mean the variable is irrelevant—it might be masked by other factors.</li>
</ul>
</section>
</div>
</div>
</section>
<section id="questions-to-answer-for-95-grade-on-challenge" class="level3">
<h3 class="anchored" data-anchor-id="questions-to-answer-for-95-grade-on-challenge">Questions to Answer for 95% Grade on Challenge</h3>
<ol start="8" type="1">
<li><strong>Reflect on Real-World Implications:</strong> For each of the two multiple regression models, assume their respective outputs/conclusions were published in academic journals and then subsequently picked up by the popular press. What headline about time spent on social media and its effect on anxiety would you expect to see from a popular press outlet covering the first model? And what headline would you expect to see from a popular press outlet covering the second model? Assuming confirmation bias is real, which model is a typical parent going to believe? Which model will Facebook, Instagram, and TikTok executives prefer?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Reflection on Real-World Implications
</div>
</div>
<div class="callout-body-container callout-body">
<section id="popular-press-headlines-based-on-each-model" class="level3">
<h3 class="anchored" data-anchor-id="popular-press-headlines-based-on-each-model">📰 Popular Press Headlines Based on Each Model</h3>
<p><strong>1. Model: Anxiety ~ StressSurvey + Time</strong></p>
<p>This model showed:</p>
<ul>
<li><strong>StressSurvey:</strong> significant positive effect</li>
<li><strong>Time:</strong> negative and non-significant effect</li>
</ul>
<p><strong>Likely headline:</strong></p>
<blockquote class="blockquote">
<p><strong><em>Study Finds More Time on Social Media May Lower Anxiety—But Stress Levels Still Matter</em></strong></p>
</blockquote>
<p><strong>Narrative angle:</strong></p>
<ul>
<li>Time spent online appears <strong>protective</strong> or <strong>neutral</strong></li>
<li>StressSurvey (possibly linked to perceived stress or platform engagement) drives anxiety</li>
<li>Suggests social media isn’t the villain—it’s how stressed you feel while using it</li>
</ul>
<p><strong>2. Model: Anxiety ~ Stress + Time</strong></p>
<p>This model recovered the true relationship:</p>
<ul>
<li><strong>Stress:</strong> strong positive effect</li>
<li><strong>Time:</strong> modest positive effect</li>
</ul>
<p><strong>Likely headline:</strong></p>
<blockquote class="blockquote">
<p><strong><em>More Time on Social Media Linked to Higher Anxiety, Study Confirms</em></strong></p>
</blockquote>
<p><strong>Narrative angle:</strong></p>
<ul>
<li>Time spent online contributes directly to anxiety</li>
<li>Stress amplifies the effect</li>
<li>Reinforces public concerns about screen time and mental health</li>
</ul>
</section>
<section id="confirmation-bias-who-believes-what" class="level3">
<h3 class="anchored" data-anchor-id="confirmation-bias-who-believes-what">🧠 Confirmation Bias: Who Believes What?</h3>
<p><strong>👨‍👩‍👧 Typical Parents</strong></p>
<ul>
<li><strong>Will likely believe the second model</strong></li>
<li>It confirms their intuition: “Too much screen time is bad for my child”</li>
<li>Aligns with broader cultural narratives about tech and mental health</li>
</ul>
<p><strong>🏢 Social Media Executives (Facebook, Instagram, TikTok)</strong></p>
<ul>
<li><strong>Will prefer the first model</strong></li>
<li>It suggests time on their platforms isn’t harmful</li>
<li>Shifts blame to user stress or external factors</li>
<li>Supports PR messaging: “We’re not the problem—stress is”</li>
</ul>
</section>
</div>
</div>
</section>
<section id="questions-to-answer-for-100-grade-on-challenge" class="level3">
<h3 class="anchored" data-anchor-id="questions-to-answer-for-100-grade-on-challenge">Questions to Answer for 100% Grade on Challenge</h3>
<ol start="9" type="1">
<li><strong>Avoiding Misleading Statistical Significance:</strong> Reflect on this tip to avoid being misled by statistically significant results: splitting the sample into meaningful subsets (“statistical regimes”), and using graphical diagnostics for linearity rather than blind reliance on “canned” regressions. Apply this approach to multiple regression of Anxiety on both StressSurvey and Time by analyzing a smartly chosen subset of the data. What specific subset did you choose and why? Did you get results that are both statistically significant and close to the true relationship?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<blockquote class="blockquote">
<p><strong>Subset chosen:</strong> StressSurvey between <strong>0</strong> and <strong>6</strong>. This regime yielded statistically significant results with coefficients that closely match the true relationship.</p>
</blockquote>
<section id="why-this-subset" class="level3">
<h3 class="anchored" data-anchor-id="why-this-subset">🎯 Why This Subset?</h3>
<p>I selected the subset where <strong>StressSurvey is between 0 and 6</strong>, which corresponds to the lower and mid-range stress levels. This regime includes:</p>
<ul>
<li>StressSurvey values: 0, 3, and 6</li>
<li>Corresponding Stress values: 0, 1, and 2</li>
</ul>
<p>This choice is strategic because:</p>
<ul>
<li><strong>StressSurvey is linearly related to Stress</strong> in this range (StressSurvey ≈ 3 × Stress)</li>
<li>The relationship between Anxiety and its predictors is likely more stable and linear</li>
<li>It avoids the high-stress regime (StressSurvey = 9 or 12), where nonlinear effects or saturation may distort inference</li>
</ul>
</section>
<section id="regression-results-subset-stresssurvey-6" class="level3">
<h3 class="anchored" data-anchor-id="regression-results-subset-stresssurvey-6">📊 Regression Results (Subset: StressSurvey ≤ 6)</h3>
<ul>
<li><strong>Intercept:</strong> ~0.0000 (not significant)</li>
<li><strong>StressSurvey coefficient:</strong> 0.3333 (p ≈ 3.09 × 10⁻⁹¹)</li>
<li><strong>Time coefficient:</strong> 0.1000 (p ≈ 1.49 × 10⁻⁸⁴)</li>
<li><strong>R-squared:</strong> 1.0000</li>
</ul>
</section>
<section id="comparison-to-true-relationship-4" class="level3">
<h3 class="anchored" data-anchor-id="comparison-to-true-relationship-4">✅ Comparison to True Relationship</h3>
<p><strong><em>True relationship:</em></strong></p>
<p><span class="math display">\[
  \text{Anxiety} = \text{Stress} + 0.1 \cdot \text{Time}
  \]</span></p>
<p><strong>Since StressSurvey = 3 × Stress in this regime:</strong></p>
<ul>
<li>The estimated coefficient of <strong>0.3333</strong> for StressSurvey aligns perfectly with the true Stress coefficient of <strong>1.0</strong></li>
<li>The <strong>Time coefficient</strong> is exactly <strong>0.1</strong></li>
<li><strong>Perfect R²</strong> and extremely low p-values confirm a strong linear fit</li>
</ul>
</section>
<section id="key-takeaways" class="level3">
<h3 class="anchored" data-anchor-id="key-takeaways">🧠 Key Takeaways</h3>
<ul>
<li><strong>Subsetting by regime</strong> revealed the true relationship that was obscured in the full model</li>
<li><strong>Blind reliance on full-sample regressions</strong> can mislead—especially when proxies like StressSurvey distort measurement</li>
</ul>
</section>
</div>
</div>
<blockquote class="blockquote">
<p>Remember: <strong>Correlation is not causation, and regression coefficients can lie!</strong> 📊</p>
</blockquote>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>